### PR TITLE
chore(deps): Update Python dependencies

### PR DESCRIPTION
**Pull request by kesara**

### CODE REVIEW

**Review by microamp — APPROVED** [review]
I see some major version upgrades, in particular, `wagtail-modeladmin`. Any breaking changes to be aware of?

Otherwise, looks okay to me.

**Comment by mgax** [comment]
> I see some major version upgrades, in particular, `wagtail-modeladmin`.

For `wagtail-modeladmin`, the [changelog](https://github.com/wagtail-nest/wagtail-modeladmin/blob/main/CHANGELOG.md#200---2024-02-05) says that the breaking changes are dropping old versions of Django and Wagtail, but the versions in use here are still supported.

However, `wagtail-modeladmin` is deprecated, and the recommended upgrade path is to use [snippets](https://docs.wagtail.org/en/stable/topics/snippets/index.html#snippets) instead. There is only one use in the codebase, which should be an easy conversion to a snippet:

https://github.com/ietf-tools/www/blob/b222992b2541417d91947fb87a7f13a3895d73c5/ietf/utils/wagtail_hooks.py#L31-L42

**Comment by kesara** [comment]
Thanks @mgax and @microamp. I'll address that.

**Comment by kesara** [comment]
I've created a #484 to address the `wagtail-modeladmin` issue.

**Pull request merged**
